# Generated by Django 5.2.15 on 2026-06-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_academicbook_file_to_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabusitem',
            options={'ordering': ['category', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='syllabusitem',
            name='category',
            field=models.CharField(choices=[('memorized_surah', 'মুখস্থ সূরা'), ('memorized_hadith', 'মুখস্থ হাদিস'), ('qirat', 'কিরাত'), ('dua_masala', 'দুআ/মাসআলা'), ('moral_story', 'নৈতিক শিক্ষা/হাদিসের গল্প')], default='qirat', max_length=20),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='lesson',
            field=models.CharField(max_length=300),
        ),
    ]
