# Generated by Django 6.0.6 on 2026-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_syllabusitem_options_syllabusitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
