# Generated by Django 6.0.6 on 2026-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_class_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='segment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
