# Generated by Django 6.0.6 on 2026-07-25 06:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_denormalized_fields(apps, schema_editor):
    """বিদ্যমান Attendance রেকর্ডে course_name/teacher_name/teacher_id/class_date
    এখনই ভরে রাখা হচ্ছে (session টিকে থাকতে থাকতেই) — যাতে পরে ৬০ দিনের পুরনো
    ClassSession মুছে গেলেও (SET_NULL) এই তথ্য হারিয়ে না যায়। কোনো Attendance
    সারি স্পর্শ/মোছা হচ্ছে না — শুধু নতুন ফিল্ড পূরণ।"""
    Attendance = apps.get_model("core", "Attendance")
    qs = Attendance.objects.select_related("session", "session__course", "session__teacher").filter(session__isnull=False)
    for att in qs:
        s = att.session
        att.class_date = s.date
        att.course_name = s.course.name if s.course_id else ""
        att.teacher_name = s.teacher.name_bn if s.teacher_id else ""
        att.teacher_id = s.teacher_id
        att.save(update_fields=["class_date", "course_name", "teacher_name", "teacher_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='core.classsession'),
        ),
        migrations.RunPython(backfill_denormalized_fields, migrations.RunPython.noop),
    ]
