# Generated by Django 6.0.6 on 2026-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendance_denormalize_for_safe_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
