# Generated by Django 6.0.6 on 2026-08-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pushsubscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('routine__isnull', False)), fields=('routine', 'date'), name='unique_routine_date_classsession'),
        ),
    ]
