# Generated by Django 6.0.6 on 2026-08-07 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_classsession_unique_routine_date_classsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineStudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(blank=True, default=list)),
                ('time', models.TimeField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_schedules', to='core.routine')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('routine', 'student')},
            },
        ),
    ]
