# Generated by Django 6.0.6 on 2026-08-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_routinestudentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='zoom_link_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='zoom_link_2',
            field=models.URLField(blank=True),
        ),
    ]
