# Generated by Django 6.0.6 on 2026-08-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_classsession_zoom_link_2_routine_zoom_link_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='force_rejoin',
            field=models.BooleanField(default=False),
        ),
    ]
