# Generated by Django 6.0.6 on 2026-08-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_classsession_force_rejoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='force_rejoin',
        ),
        migrations.AddField(
            model_name='classsession',
            name='join_mode_override',
            field=models.CharField(choices=[('auto', 'স্বয়ংক্রিয়'), ('join', 'জোর করে জয়েন লিংক'), ('rejoin', 'জোর করে রিজয়েন লিংক')], default='auto', max_length=10),
        ),
    ]
