# Generated by Django 6.0.6 on 2026-08-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_classsession_force_rejoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='স্টুডেন্ট আইডি'),
        ),
    ]
