# Generated by Django 6.0.6 on 2026-08-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabusSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_sheet', to='core.course')),
            ],
        ),
    ]
