# Generated by Django 6.0.6 on 2026-08-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_syllabus_sheet_english_headers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturetopic',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='lecturetopic',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lecturetopic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
