# Generated by Django 6.0.6 on 2026-08-23 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_lecturetopic_options_lecturetopic_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covered', models.CharField(choices=[('pending', 'বাকি'), ('covered', 'কভার ✔'), ('missed', 'বাদ ✘')], default='pending', max_length=8)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='topic_coverages', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='core.lecturetopic')),
            ],
            options={
                'unique_together': {('topic', 'student')},
            },
        ),
    ]
