# Generated by Django 6.0.6 on 2026-08-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_topiccoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_students', to=settings.AUTH_USER_MODEL, verbose_name='কার কাছে পড়ে'),
        ),
    ]
