# Generated by Django 6.0.6 on 2026-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='duemonth',
            name='waived',
            field=models.BooleanField(default=False, verbose_name='মওকুফ'),
        ),
        migrations.AddField(
            model_name='duemonth',
            name='waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duemonth',
            name='waived_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
