# Generated by Django 6.0.6 on 2026-08-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_due_waived'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='teacher_finished',
            field=models.BooleanField(default=False),
        ),
    ]
