# Generated by Django 6.0.6 on 2026-08-26 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_class_teacher_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_users', to='core.admission', verbose_name='যে আবেদন থেকে'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_students', to='core.course', verbose_name='ট্রায়ালের কোর্স'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_until',
            field=models.DateField(blank=True, help_text='এই তারিখ পর্যন্ত ট্রায়াল চলবে', null=True, verbose_name='ট্রায়ালের মেয়াদ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'পরিচালক'), ('admin', 'এডমিন'), ('teacher', 'উস্তাদ/উস্তাদা'), ('student', 'স্টুডেন্ট'), ('trial', 'ট্রায়াল শিক্ষার্থী')], default='student', max_length=10),
        ),
    ]
