# Generated by Django 6.0.6 on 2026-08-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_trial_guest_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='ট্রায়ালের পরিকল্পনা'),
        ),
    ]
