# Generated by Django 6.0.6 on 2026-08-26 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_trial_lesson_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('strengths', models.TextField(blank=True, default='', verbose_name='শক্তির দিক')),
                ('work_on', models.TextField(blank=True, default='', verbose_name='যা নিয়ে কাজ করতে হবে')),
                ('advice', models.TextField(blank=True, default='', verbose_name='উস্তাদের পরামর্শ')),
                ('recommended_level', models.CharField(blank=True, default='', max_length=60, verbose_name='উপযুক্ত স্তর')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_reports_written', to=settings.AUTH_USER_MODEL)),
                ('recommended_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_recommendations', to='core.course', verbose_name='উপযুক্ত কোর্স')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'trial'}, on_delete=django.db.models.deletion.CASCADE, related_name='trial_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
