# Generated by Django 6.0.6 on 2026-08-26 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_trial_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialreport',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialreport',
            name='offer_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='মাসিক ফি'),
        ),
        migrations.AddField(
            model_name='trialreport',
            name='offer_schedule',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='প্রস্তাবিত দিন ও সময়'),
        ),
        migrations.AddField(
            model_name='trialreport',
            name='offer_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_offers', to=settings.AUTH_USER_MODEL, verbose_name='প্রস্তাবিত উস্তাদ'),
        ),
        migrations.AddField(
            model_name='trialreport',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
