# Generated by Django 6.0.6 on 2026-08-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_trial_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label_bn', models.CharField(max_length=80, verbose_name='বাংলা নাম (উস্তাদ দেখবেন)')),
                ('label_en', models.CharField(max_length=80, verbose_name='ইংরেজি নাম (পরিবার দেখবেন)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
