# Generated by Django 6.0.6 on 2026-08-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_seed_trial_score_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialscoreitem',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='ইংরেজি নাম (পরিবার দেখবেন)'),
        ),
    ]
