# Generated by Django 6.0.6 on 2026-08-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_trial_score_label_en_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='দারসের শিরোনাম')),
                ('title_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='আরবি শিরোনাম')),
                ('kind', models.CharField(choices=[('memorization', 'মুখস্থ (হিফজ)'), ('qaida', 'কায়েদা'), ('tajweed', 'তাজবীদ'), ('reading', 'তিলাওয়াত'), ('islamic', 'ইসলামিক শিক্ষা'), ('other', 'অন্যান্য')], default='memorization', max_length=14)),
                ('age_from', models.PositiveSmallIntegerField(default=5, verbose_name='বয়স — থেকে')),
                ('age_to', models.PositiveSmallIntegerField(default=7, verbose_name='বয়স — পর্যন্ত')),
                ('duration_min', models.PositiveIntegerField(default=25, verbose_name='আনুমানিক সময় (মিনিট)')),
                ('objectives', models.TextField(blank=True, default='', verbose_name='কাঙ্ক্ষিত ফল')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('ready', 'প্রস্তুত'), ('published', 'প্রকাশিত'), ('archived', 'সংরক্ষিত')], default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course')),
            ],
            options={
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, default='', max_length=120, verbose_name='এই ধাপের অংশ')),
                ('teacher_says', models.TextField(blank=True, default='', verbose_name='উস্তাদ বলবেন')),
                ('teacher_does', models.TextField(blank=True, default='', verbose_name='উস্তাদ করবেন')),
                ('student_does', models.TextField(blank=True, default='', verbose_name='শিক্ষার্থী করবে')),
                ('expected', models.TextField(blank=True, default='', verbose_name='প্রত্যাশিত সাড়া')),
                ('correction', models.TextField(blank=True, default='', verbose_name='ভুল হলে')),
                ('note', models.TextField(blank=True, default='', verbose_name='উস্তাদের টীকা')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='আনুমানিক সময় (সেকেন্ড)')),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.lesson')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_steps', to='core.lecturetopic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StepSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('title', 'শিরোনাম'), ('verse', 'আয়াত'), ('letters', 'হরফ'), ('listen', 'শোনো'), ('repeat', 'আমার সাথে বলো'), ('your_turn', 'তুমি বলো'), ('question', 'প্রশ্ন'), ('meaning', 'অর্থ'), ('visual', 'ছবি'), ('activity', 'খেলা'), ('reminder', 'মনে রেখো'), ('praise', 'শাবাশ'), ('review', 'পুনরাবৃত্তি'), ('homework', 'বাড়ির কাজ'), ('end', 'সমাপ্তি'), ('blank', 'খালি পর্দা')], default='title', max_length=12)),
                ('heading', models.CharField(blank=True, default='', max_length=160)),
                ('arabic', models.TextField(blank=True, default='')),
                ('arabic_locked', models.BooleanField(default=False, verbose_name='আরবি যাচাইকৃত ও সুরক্ষিত')),
                ('translit', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('audio', models.CharField(blank=True, default='', max_length=500)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='core.lessonstep')),
            ],
        ),
    ]
