# Generated by Django 6.0.6 on 2026-08-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_seed_sample_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learning', 'শিখছে'), ('review', 'পুনরাবৃত্তি দরকার'), ('mastered', 'মুখস্থ হয়েছে')], default='learning', max_length=10)),
                ('times_taught', models.PositiveIntegerField(default=0, verbose_name='কয় দিন পড়ানো হয়েছে')),
                ('last_taught', models.DateField(blank=True, null=True, verbose_name='সর্বশেষ যেদিন')),
                ('last_step', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='', verbose_name='উস্তাদের মন্তব্য')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_taught', '-updated_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
