# Generated by Django 6.0.6 on 2026-08-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_lesson_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='core.lecturetopic', verbose_name='দারস পরিকল্পনার টপিক'),
        ),
    ]
